modified mlops pipeline

diff --git a/.github/workflows/mlops-ci.yml b/.github/workflows/mlops-ci.yml
--- a/.github/workflows/mlops-ci.yml
+++ b/.github/workflows/mlops-ci.yml
@@ -26,15 +26,21 @@ jobs:
           python -m pip install --upgrade pip
           pip install -r requirements.txt
 
+      - name: Ensure models directory exists
+        run: mkdir -p models
+
       - name: Train the Model
-        run: |
-         python scripts/train.py  
+        run: python scripts/train.py
+
+      - name: Debug model directory
+        run: ls -R models || echo "models directory not found"
 
       - name: Upload trained model as artifact
         uses: actions/upload-artifact@v4
         with:
           name: trained-model
           path: models/model.pkl
+          if-no-files-found: error  # Fails the workflow if model.pkl is missing
 
       - name: Upload MLflow artifacts
         uses: actions/upload-artifact@v4
@@ -43,8 +49,7 @@ jobs:
           path: mlruns/
 
       - name: Build Docker image
-        run: |
-          docker build -t mlops-app -f ./api/Dockerfile .
+        run: docker build -t mlops-app -f ./api/Dockerfile .
 
       - name: Push Docker image
         run: |
